/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_karashok_avstudydemo_ffmpeg_utils_PushStreamU */

#ifndef _Included_com_karashok_avstudydemo_ffmpeg_utils_PushStreamU
#define _Included_com_karashok_avstudydemo_ffmpeg_utils_PushStreamU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_karashok_avstudydemo_ffmpeg_utils_PushStreamU
 * Method:    push
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_karashok_avstudydemo_ffmpeg_1utils_PushStreamU_push
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
