/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_karashok_avstudydemo_ffmpegu_FFVersionU */

#ifndef _Included_com_karashok_avstudydemo_ffmpegu_FFVersionU
#define _Included_com_karashok_avstudydemo_ffmpegu_FFVersionU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_karashok_avstudydemo_ffmpegu_FFVersionU
 * Method:    avcodecVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_karashok_avstudydemo_ffmpegu_FFVersionU_avcodecVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
