/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_karashok_avstudydemo_ffmpegu_FFPlayerU */

#ifndef _Included_com_karashok_avstudydemo_ffmpegu_FFPlayerU
#define _Included_com_karashok_avstudydemo_ffmpegu_FFPlayerU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_karashok_avstudydemo_ffmpegu_FFPlayerU
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_karashok_avstudydemo_ffmpegu_FFPlayerU_render
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_karashok_avstudydemo_ffmpegu_FFPlayerU
 * Method:    sound
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_karashok_avstudydemo_ffmpegu_FFPlayerU_sound
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
