/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_karashok_avstudydemo_ffmpegu_FFVideoU */

#ifndef _Included_com_karashok_avstudydemo_ffmpegu_FFVideoU
#define _Included_com_karashok_avstudydemo_ffmpegu_FFVideoU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_karashok_avstudydemo_ffmpegu_FFVideoU
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_karashok_avstudydemo_ffmpegu_FFVideoU_decode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
